### ISSUE TITLE
Warning: Illegal offset type in isset or empty in /classes/Tools.php

### ISSUE THREAD

**Issue by jorgeceuta** [Ha99y/PrestaShop-modules-CleanURLs#5]
I have 1.6.1.7 and get the Warning: "Illegal offset type in isset or empty in /home/if1mriow/public_html/classes/Tools.php on line 1397" when go in to subcategory page.
Any aidea?

**Comment by pwnsdx** [comment]
@jorgeceuta This repo is dead. Use https://github.com/faktiva/prestashop-clean-urls instead
